[[HepMC3]]
arch = "aarch64"
git-tree-sha1 = "bb5bb19c5662fd38fa14f669c11e2397ebe28690"
os = "macos"

    [[HepMC3.download]]
    sha256 = "98c550bab86e3081814cc1269de328fdb7ba4ae15ffa6f7543d1f42271bd4109"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.2.7+0/HepMC3.v3.2.7.aarch64-apple-darwin.tar.gz"
[[HepMC3]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7d2b81820959227ef4b7e99c0a354681fb4d2080"
libc = "glibc"
os = "linux"

    [[HepMC3.download]]
    sha256 = "d3e8e712af9a283217919e730fe79dc7686b8db28762c693aaeae0853de1f2a1"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.2.7+0/HepMC3.v3.2.7.aarch64-linux-gnu-cxx03.tar.gz"
[[HepMC3]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2d1ab68d09949948a37fb2ee10921a3253ba8fe5"
libc = "glibc"
os = "linux"

    [[HepMC3.download]]
    sha256 = "53ff9cde5d23f3d288b225d6b94fe5ac64f8409b8455e2f00b387cfe9d065683"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.2.7+0/HepMC3.v3.2.7.aarch64-linux-gnu-cxx11.tar.gz"
[[HepMC3]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "71cbb97a2316a4c69a61b6c5158d247555bf2f08"
libc = "musl"
os = "linux"

    [[HepMC3.download]]
    sha256 = "cc514273a9f30567bbc1b7a852b28722a18653341919f98c1a8736c3706e4b65"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.2.7+0/HepMC3.v3.2.7.aarch64-linux-musl-cxx03.tar.gz"
[[HepMC3]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f00bdcc02bef3829a9da8940302537700a69995a"
libc = "musl"
os = "linux"

    [[HepMC3.download]]
    sha256 = "e0621749fdd1761318602e3c6d3cf7191b83704c60861e76a62ed7dc85fdafe4"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.2.7+0/HepMC3.v3.2.7.aarch64-linux-musl-cxx11.tar.gz"
[[HepMC3]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "42cdfb348673ab63557063642089fb795756ff6b"
libc = "glibc"
os = "linux"

    [[HepMC3.download]]
    sha256 = "6185f25273a46310a7c5689c995b2dcdc33bf682110515f93b84bc53d6a0b025"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.2.7+0/HepMC3.v3.2.7.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[HepMC3]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9a517ed89f731470d62169d30a17703e1f4d6cff"
libc = "glibc"
os = "linux"

    [[HepMC3.download]]
    sha256 = "15190fd4d5143038923086ba127a7a8812560218f656559b5cbbddb6c353667c"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.2.7+0/HepMC3.v3.2.7.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[HepMC3]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5eafa6c040de53644c086634087e57cfb9165553"
libc = "musl"
os = "linux"

    [[HepMC3.download]]
    sha256 = "7c3399d1a9bbeaac86c3daf9bba7dcf29ff83bf0a8a9c6ec5f7c46ceaa496944"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.2.7+0/HepMC3.v3.2.7.armv7l-linux-musleabihf-cxx03.tar.gz"
[[HepMC3]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e20663a163e2d773564c7e4f55254d22f3e84633"
libc = "musl"
os = "linux"

    [[HepMC3.download]]
    sha256 = "dd47d3f40ef1c684f4ae95230efd4e14b8f50ef7d67f1c3ab3bcf2d325e7c8c5"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.2.7+0/HepMC3.v3.2.7.armv7l-linux-musleabihf-cxx11.tar.gz"
[[HepMC3]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f821099052bf8b2a812ad59e6d56f04d96402726"
libc = "glibc"
os = "linux"

    [[HepMC3.download]]
    sha256 = "c57cca570805fc808aa2f06368fdc33e6d21f556acea9fc73121e9f6143efe8b"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.2.7+0/HepMC3.v3.2.7.i686-linux-gnu-cxx03.tar.gz"
[[HepMC3]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ca19369819a75707ca4729f99d764f890b8a7d83"
libc = "glibc"
os = "linux"

    [[HepMC3.download]]
    sha256 = "69d3b09a7011956806a52d0e8269a35a96a69afcbaba8137840e1405c3eca99e"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.2.7+0/HepMC3.v3.2.7.i686-linux-gnu-cxx11.tar.gz"
[[HepMC3]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "65dcc9a1701c53dd1fbdf384650ce7066391c4d2"
libc = "musl"
os = "linux"

    [[HepMC3.download]]
    sha256 = "ef89a442cc566f250afbc1a72ead42fccbea6bd7491f073f12d4ccc16aab1891"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.2.7+0/HepMC3.v3.2.7.i686-linux-musl-cxx03.tar.gz"
[[HepMC3]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d2cc4b0b9e14c4fd40fedfe015725c191e3f8af5"
libc = "musl"
os = "linux"

    [[HepMC3.download]]
    sha256 = "d63a3a83b8472744f7fafc9e8a7f166e1a370382981f6643509f8d0c0cf1b621"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.2.7+0/HepMC3.v3.2.7.i686-linux-musl-cxx11.tar.gz"
[[HepMC3]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "52d63219618619cb044ad5959a07e17547dd7c61"
libc = "glibc"
os = "linux"

    [[HepMC3.download]]
    sha256 = "407af501cb2bbdd267ac4331a99899290422ffaa66dfa14a92b6a013f80dab1c"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.2.7+0/HepMC3.v3.2.7.powerpc64le-linux-gnu-cxx03.tar.gz"
[[HepMC3]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1b97755476c045a7ef6dbed065c261587c9fb68f"
libc = "glibc"
os = "linux"

    [[HepMC3.download]]
    sha256 = "a34a9d1256ff1c9d31a86758f878dcbfc0278d275dcd565a638981db9f9c3111"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.2.7+0/HepMC3.v3.2.7.powerpc64le-linux-gnu-cxx11.tar.gz"
[[HepMC3]]
arch = "x86_64"
git-tree-sha1 = "118e09965fe406a2685f708480893819a23a2d5e"
os = "macos"

    [[HepMC3.download]]
    sha256 = "36e0268100dfcb2ff907095bd4d6557cc88e7d2fa0feb5f2be7ff3dc8109267e"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.2.7+0/HepMC3.v3.2.7.x86_64-apple-darwin.tar.gz"
[[HepMC3]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8bfaa9ca3ec001bdba768731dece9a1282919d69"
libc = "glibc"
os = "linux"

    [[HepMC3.download]]
    sha256 = "02d9f116fb47d593b776d39a11c6cba3b9af519e54a02daf7edb34ba15cd513b"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.2.7+0/HepMC3.v3.2.7.x86_64-linux-gnu-cxx03.tar.gz"
[[HepMC3]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "94317aa3e55d4e5a7026c579392afb8236584d32"
libc = "glibc"
os = "linux"

    [[HepMC3.download]]
    sha256 = "967366a8660bb09bdc1256a8936f944d9af8c785a098aef21300118b28ceb285"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.2.7+0/HepMC3.v3.2.7.x86_64-linux-gnu-cxx11.tar.gz"
[[HepMC3]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ae9ac1e1049934ce0584298b43c23285fc8864a2"
libc = "musl"
os = "linux"

    [[HepMC3.download]]
    sha256 = "fd71ca00eca711d38e5b71856eb11c02a19261f4a24760bf4f9ed9552c8c1926"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.2.7+0/HepMC3.v3.2.7.x86_64-linux-musl-cxx03.tar.gz"
[[HepMC3]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ccc10b000b3343e3569cd8b003c9ddf58c25ae2b"
libc = "musl"
os = "linux"

    [[HepMC3.download]]
    sha256 = "33036749d962611917b74a8ba2548fd01d7c67d4b8c3d5258b5dfd8265ed280c"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.2.7+0/HepMC3.v3.2.7.x86_64-linux-musl-cxx11.tar.gz"
