[[HepMC3]]
arch = "aarch64"
git-tree-sha1 = "4dc263323848af7b7f35ea812bed4ae8d0aefe0e"
os = "macos"

    [[HepMC3.download]]
    sha256 = "1088d0c488480eca5c1e454ee109e075e67db4296abeb883077ee6f67feb09a2"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.3.0+0/HepMC3.v3.3.0.aarch64-apple-darwin.tar.gz"
[[HepMC3]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bc69811aee99953d93872a2817177f887deffe4b"
libc = "glibc"
os = "linux"

    [[HepMC3.download]]
    sha256 = "26c3cc2d0ec6ebf746543e1d359954f2f037988ad451fb2dd2078df10fdb044e"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.3.0+0/HepMC3.v3.3.0.aarch64-linux-gnu-cxx03.tar.gz"
[[HepMC3]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "72fdc8c19354e6730dba8de966bc34449efe09e5"
libc = "glibc"
os = "linux"

    [[HepMC3.download]]
    sha256 = "8fd1a4bfa40325ef5435a821c1f7f5d0e5944ae8e6b2ffd72a5b88a8789f01a9"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.3.0+0/HepMC3.v3.3.0.aarch64-linux-gnu-cxx11.tar.gz"
[[HepMC3]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e3d49d3f7b2420d626bac82ce3ec773f436712c8"
libc = "musl"
os = "linux"

    [[HepMC3.download]]
    sha256 = "4526d76ddcf2d1da9b4c0226f02cf7f9b115e244ff20243277c31335f306bfc2"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.3.0+0/HepMC3.v3.3.0.aarch64-linux-musl-cxx03.tar.gz"
[[HepMC3]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0b50fb9997269b047f25a2405abac1130f045b23"
libc = "musl"
os = "linux"

    [[HepMC3.download]]
    sha256 = "8fe31d2b4e3e8aeaa252c2088c380ecf2c2ad32cb23107a7d075603bb289f66a"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.3.0+0/HepMC3.v3.3.0.aarch64-linux-musl-cxx11.tar.gz"
[[HepMC3]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2639ecbe08564db069c3ba757499b5de9e98fa18"
libc = "glibc"
os = "linux"

    [[HepMC3.download]]
    sha256 = "1a00fb3ef027940fbc689bb4e690d65f318d065f05552497412e8d13384b22f2"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.3.0+0/HepMC3.v3.3.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[HepMC3]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7f1f0fda304675f389fc6fab2eb37733394439ec"
libc = "glibc"
os = "linux"

    [[HepMC3.download]]
    sha256 = "d433ecb36fdbc1896b87fcb55ad2d557a44ed36094cfbfa0479f5ae34e9464b2"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.3.0+0/HepMC3.v3.3.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[HepMC3]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ef28c1e3e96f263ad54b090993ccb87a04fd7130"
libc = "musl"
os = "linux"

    [[HepMC3.download]]
    sha256 = "7e07becc467a6d0d00b32bac09dcab9b8bcef62ba685c126eae34192dc3ea92d"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.3.0+0/HepMC3.v3.3.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[HepMC3]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5a5454fb0ba0261459d0fcff8d623ac53206c5f2"
libc = "musl"
os = "linux"

    [[HepMC3.download]]
    sha256 = "1b8a8c9ba0ae847941439b299b337de52acf1f9b0accfe73abeda99c1d526625"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.3.0+0/HepMC3.v3.3.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[HepMC3]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "92452068c49db6bd340e1b822ea61d1b48e6bec8"
libc = "glibc"
os = "linux"

    [[HepMC3.download]]
    sha256 = "abd1f2bc4dfab41cf9fb7e31233f0f5077959512d3bf681f0938a33a1036c542"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.3.0+0/HepMC3.v3.3.0.i686-linux-gnu-cxx03.tar.gz"
[[HepMC3]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "872dff768b5c7a857ce52ae70e3bb79dfd84bc80"
libc = "glibc"
os = "linux"

    [[HepMC3.download]]
    sha256 = "bcccfdf8ea24ff9b953e63cc791d32a59bc9f712a42241e50702c083b3ca70b6"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.3.0+0/HepMC3.v3.3.0.i686-linux-gnu-cxx11.tar.gz"
[[HepMC3]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "75c258c696be8e5d316e8cca7dba5510127b0452"
libc = "musl"
os = "linux"

    [[HepMC3.download]]
    sha256 = "8d0dea58a41e4095331b9028f4f7545a7210ce1e94db2101cf7ba1719c30eb2f"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.3.0+0/HepMC3.v3.3.0.i686-linux-musl-cxx03.tar.gz"
[[HepMC3]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3ba41b7adde8353f29fdea3afe19dd16bc10646b"
libc = "musl"
os = "linux"

    [[HepMC3.download]]
    sha256 = "1e548afb40fab089a34ad7a7563e34941529084025c0fbb764219a75d1e6d735"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.3.0+0/HepMC3.v3.3.0.i686-linux-musl-cxx11.tar.gz"
[[HepMC3]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fde0b1f7cedb9b10cad53ed55345b00fd6fa296e"
libc = "glibc"
os = "linux"

    [[HepMC3.download]]
    sha256 = "cc99547f3fc90042870441c1e1cdf77e9b8b22d21f074a7ba8c9170865f7230b"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.3.0+0/HepMC3.v3.3.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[HepMC3]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dff495790ca24b26880afcebf0c0191c9f2e6735"
libc = "glibc"
os = "linux"

    [[HepMC3.download]]
    sha256 = "30d81b722e947578a6702b74bd10bbba829e96f85b45e07381da32099d5e043a"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.3.0+0/HepMC3.v3.3.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[HepMC3]]
arch = "x86_64"
git-tree-sha1 = "e594d2eb58d058362f1ddc846f42621345899c63"
os = "macos"

    [[HepMC3.download]]
    sha256 = "17458c0b04d8e0646b6e6083d0d229916f564888d1ad58f15647a25fd9c55196"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.3.0+0/HepMC3.v3.3.0.x86_64-apple-darwin.tar.gz"
[[HepMC3]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b4a3e350799397526f30135433691f1f35068171"
libc = "glibc"
os = "linux"

    [[HepMC3.download]]
    sha256 = "351003578ad5997114aeda5c772b4f315ad6358f7d7d47869792a5a565860b35"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.3.0+0/HepMC3.v3.3.0.x86_64-linux-gnu-cxx03.tar.gz"
[[HepMC3]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7594d64d7c28f9689b484bf4d09af6dbb8b5123c"
libc = "glibc"
os = "linux"

    [[HepMC3.download]]
    sha256 = "10f432dd15f11edd5e3e95a666aee2459dfa7c91cb52be6e379e85e7f4be3559"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.3.0+0/HepMC3.v3.3.0.x86_64-linux-gnu-cxx11.tar.gz"
[[HepMC3]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "055863f19a07613c823e6bc2f77dface01ce858d"
libc = "musl"
os = "linux"

    [[HepMC3.download]]
    sha256 = "2b4dbf13def9b2c29153f717ccbe51339eb746244ee81128f0c8ac450c3907a5"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.3.0+0/HepMC3.v3.3.0.x86_64-linux-musl-cxx03.tar.gz"
[[HepMC3]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bbeae1d09ad769e7b0c0f3a8bb7b33b9ccc1e8fa"
libc = "musl"
os = "linux"

    [[HepMC3.download]]
    sha256 = "aa046f9110398c204195e0ef60b3124471a5311ba76039b318df7146c7c1367b"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.3.0+0/HepMC3.v3.3.0.x86_64-linux-musl-cxx11.tar.gz"
