[[HepMC3]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "53871227fac5c6d891d9de7e14c29f8d06bbd5ab"
libc = "glibc"
os = "linux"

    [[HepMC3.download]]
    sha256 = "3141f18ae490a9b1cd893e619a5a977f18f187a4ce1ebaf5fb1f8d3372ced21d"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.2.5+0/HepMC3.v3.2.5.aarch64-linux-gnu-cxx03.tar.gz"
[[HepMC3]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1b780ff622e8e77c5c0196a072e9196f40b7437b"
libc = "glibc"
os = "linux"

    [[HepMC3.download]]
    sha256 = "03e8eb21823be7d1d456a4a6e6ba4c603a830501e8ffac47b114b4a210c55b33"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.2.5+0/HepMC3.v3.2.5.aarch64-linux-gnu-cxx11.tar.gz"
[[HepMC3]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "61c217bbb2087d4e94fb1349fcd7924df3efb032"
libc = "musl"
os = "linux"

    [[HepMC3.download]]
    sha256 = "67207178c6bc69aa74ed78eebec75fdb254c8d1f80b096b439f1110beee46c32"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.2.5+0/HepMC3.v3.2.5.aarch64-linux-musl-cxx03.tar.gz"
[[HepMC3]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "952abb249b8c17bb1741e87c5ea496963998d7b2"
libc = "musl"
os = "linux"

    [[HepMC3.download]]
    sha256 = "3cee2355c21eb0e0a2668bc09e929c3fe0fda943ae34010b3c7cbb6d41a8a312"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.2.5+0/HepMC3.v3.2.5.aarch64-linux-musl-cxx11.tar.gz"
[[HepMC3]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0ce4cdb5ee36b94ef5a69590e8350a88102aadfa"
libc = "glibc"
os = "linux"

    [[HepMC3.download]]
    sha256 = "91fedfd5a72466a3cda8187fffe663e36ad97cba1f1fcd59169662045e5f1de1"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.2.5+0/HepMC3.v3.2.5.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[HepMC3]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bfa3680ac4a7738c921437ce40a66e7c9c1ecc2f"
libc = "glibc"
os = "linux"

    [[HepMC3.download]]
    sha256 = "4fe924963d617a303fc53bc92ad0057a330a3d82c3b1ef81db3d12c12522ebdb"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.2.5+0/HepMC3.v3.2.5.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[HepMC3]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fa394771784eece01f95c62ffae87cc7a18c9580"
libc = "musl"
os = "linux"

    [[HepMC3.download]]
    sha256 = "e7949dc226c9bd7e530aa014184a9a42966d67336a948ed15598d5731384c721"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.2.5+0/HepMC3.v3.2.5.armv7l-linux-musleabihf-cxx03.tar.gz"
[[HepMC3]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "56850137d2708dd4d442f4de91a82b695bbc16ce"
libc = "musl"
os = "linux"

    [[HepMC3.download]]
    sha256 = "4480b75dd3e50f14d6d095f86d4bb555fa424ebe64def4b7504baf67e24308a9"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.2.5+0/HepMC3.v3.2.5.armv7l-linux-musleabihf-cxx11.tar.gz"
[[HepMC3]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7cb25f9e90f8e5568bbd05327843a3d567e080bc"
libc = "glibc"
os = "linux"

    [[HepMC3.download]]
    sha256 = "dd73cd144bcf23b388b90eb0edd85f978e5701d84e9050785c1cfd1c41f0744d"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.2.5+0/HepMC3.v3.2.5.i686-linux-gnu-cxx03.tar.gz"
[[HepMC3]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a5587d1746a4998aa7471d19e319016a841456f0"
libc = "glibc"
os = "linux"

    [[HepMC3.download]]
    sha256 = "40601c12a25c0b6cd5f108ff4b204d96be07ff1b8386e9c8a8cbd3e1eb1fce1e"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.2.5+0/HepMC3.v3.2.5.i686-linux-gnu-cxx11.tar.gz"
[[HepMC3]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fa2b99047e5511aff724bc92330ce4751746ca25"
libc = "musl"
os = "linux"

    [[HepMC3.download]]
    sha256 = "8637f0c88133dbc42fc0e5dc473abc05d9b3e686d90238d5e9627ab115803a81"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.2.5+0/HepMC3.v3.2.5.i686-linux-musl-cxx03.tar.gz"
[[HepMC3]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd3c2ec6424072f57024faf9a8f0dace5e445df8"
libc = "musl"
os = "linux"

    [[HepMC3.download]]
    sha256 = "b4ffd4f9fa6cf57b32082de90de9531f303326de778228888a84c376c9447632"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.2.5+0/HepMC3.v3.2.5.i686-linux-musl-cxx11.tar.gz"
[[HepMC3]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8da0ed402ce61e6b46928f6b0e187ae68750a203"
libc = "glibc"
os = "linux"

    [[HepMC3.download]]
    sha256 = "1682c2c33c1256c5dff845b4668f314152025dd78ea30f9b7184a442ee781b6b"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.2.5+0/HepMC3.v3.2.5.powerpc64le-linux-gnu-cxx03.tar.gz"
[[HepMC3]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c282b0596f7d83ad8d7f53507862f89b35fd32b8"
libc = "glibc"
os = "linux"

    [[HepMC3.download]]
    sha256 = "9d2bf3665f7680ae2d4c5dc8d1bfa9594d9489e5b66a03e6ce44306279b9d035"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.2.5+0/HepMC3.v3.2.5.powerpc64le-linux-gnu-cxx11.tar.gz"
[[HepMC3]]
arch = "x86_64"
git-tree-sha1 = "e9777d3e50d32e3ec5c83abe69f6b16d4a71ca51"
os = "macos"

    [[HepMC3.download]]
    sha256 = "f2701b1b713ecede311245589910c5e61e6c5f2d496d0542d22b3250eea63847"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.2.5+0/HepMC3.v3.2.5.x86_64-apple-darwin.tar.gz"
[[HepMC3]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a95c8ef7820eb04408ff324539c8f0f41dec2d64"
libc = "glibc"
os = "linux"

    [[HepMC3.download]]
    sha256 = "4ea580308dd46253d3fd0c1b04641370ca8513ff617e149782c64309c1ab576d"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.2.5+0/HepMC3.v3.2.5.x86_64-linux-gnu-cxx03.tar.gz"
[[HepMC3]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "25c2233427c0e1b9089b43fa60e115ae8b2d154b"
libc = "glibc"
os = "linux"

    [[HepMC3.download]]
    sha256 = "9d4c799936e2ed3b4d5e09a4cc8b587b26baeae2a3a26761dd5bed17e5cb3f70"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.2.5+0/HepMC3.v3.2.5.x86_64-linux-gnu-cxx11.tar.gz"
[[HepMC3]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f77da29edaa28db2f312020a24872a1c9e3e37d4"
libc = "musl"
os = "linux"

    [[HepMC3.download]]
    sha256 = "2fd0f62b212f3918c84f45e5b12d75463d55c73e8e4c8eef08f23dd94b6c286f"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.2.5+0/HepMC3.v3.2.5.x86_64-linux-musl-cxx03.tar.gz"
[[HepMC3]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9f9e717c7247ce332684b0e85c7dc1b3e9fa0ce4"
libc = "musl"
os = "linux"

    [[HepMC3.download]]
    sha256 = "1ed03bba1c3f9e2c1a5fea3e7f114bedd9bb7da7a9bc2d739704c500685b0e8b"
    url = "https://github.com/JuliaBinaryWrappers/HepMC3_jll.jl/releases/download/HepMC3-v3.2.5+0/HepMC3.v3.2.5.x86_64-linux-musl-cxx11.tar.gz"
