# Autogenerated wrapper script for HepMC3_jll for aarch64-apple-darwin
export libHepMC3, libHepMC3search

JLLWrappers.@generate_wrapper_header("HepMC3")
JLLWrappers.@declare_library_product(libHepMC3, "@rpath/libHepMC3.3.dylib")
JLLWrappers.@declare_library_product(libHepMC3search, "@rpath/libHepMC3search.5.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libHepMC3,
        "lib/libHepMC3.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libHepMC3search,
        "lib/libHepMC3search.5.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
